# Generated by Django 5.1.3 on 2024-11-13 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_lib_api', '0002_remove_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookauthor',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='bookowner',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='bookauthor',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='bookowner',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookAuthor',
        ),
        migrations.DeleteModel(
            name='BookOwner',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
