version: "3.7"
services:

  postgresql:
    image: postgres:13
    environment:
      POSTGRES_USER: ${MY_USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    container_name: "app"
    image: api:5
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://${MY_USER}:${PASSWORD}@postgresql:5432/${DATABASE}
    ports:
      - "8000:8000"
    depends_on:
      postgresql:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000" 
    
